FIND_LIBRARY(DEVIL_LIBRARY1 IL ENV LD_LIBRARY_PATH)
FIND_LIBRARY(DEVIL_LIBRARY2 ILU ENV LD_LIBRARY_PATH)
FIND_LIBRARY(DEVIL_LIBRARY3 ILUT ENV LD_LIBRARY_PATH)
SET(DEVIL_INCLUDE_DIR /usr/include/IL/)
SET(DEVIL_LIBRARIES ${DEVIL_LIBRARY1}
			${DEVIL_LIBRARY2}
			${DEVIL_LIBRARY3})


SET( DEVIL_FOUND "NO" )
IF(DEVIL_LIBRARIES )
    SET( DEVIL_FOUND "YES" )
ENDIF(DEVIL_LIBRARIES)
